keybinding:
  universal:
    prevItem-alt: 'l' # go one line up
    nextItem-alt: 'k' # go one line down
    scrollLeft: '<c-j>' # scroll left within list view
    # scrollRight: '<c-\\\;>' # scroll right within list view
    prevBlock-alt: 'j' # goto the previous block / panel
    nextBlock-alt: ';' # goto the next block / panel
    scrollUpMain-alt1: '<c-l>' # main panel scroll up
    scrollDownMain-alt1: '<c-k>' # main panel scroll down
